config/routes.rb
Rails.application.routes.draw do
  get 'charges/new'

  get 'charges/create'

  get 'carts/show'

  root to: 'visitors#home'

  # ----------------- Charges ------------------
  resources :charges, only: [:new, :create]
  # --------------------------------------------

  # ------------------ Cart --------------------
  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
    get 'clear', to: 'carts#clear', as: :clear
  end
  # --------------------------------------------

  # -------------- Reservations ----------------
  resources :reservations, only: [:index, :new, :create]
  get 'reservations/table' => 'reservations#table', as: :table_reservation
  get 'reservations/lesson' => 'reservations#lesson', as: :lesson_reservation
  get 'dashboard/admin' => 'reservations#dashboard', as: :admin_dashboard
  delete 'reservations' => 'reservations#delete'
  # --------------------------------------------

  # ------------  User and Session -------------
  resources :users
  devise_for :users, skip: [:sessions]
  devise_scope :user do
    get 'signin', to: 'devise/sessions#new', as: :new_user_session
    post 'signin', to: 'devise/sessions#create', as: :user_session
    delete 'signin', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  get 'profile' => 'users#profile'
  post 'membership' => 'users#membership'
  # --------------------------------------------


  # ------------------ Products ----------------
  resources :products
  # --------------------------------------------
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :time_blocks
  has_many :day_blocks, foreign_key: :coach_id, class_name: "DayBlock"
  has_many :reservations
  has_many :purchases

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum membership_type: [:monthly, :quarterly, :yearly]

  def week_reservations(start_date)
    end_date = start_date + 7.days
    reservations = self.reservations
                      .where('scheduled_for >= ?', start_date.beginning_of_day)
                      .where('scheduled_for < ?', end_date.end_of_day)
                      .where(type_play?: true)
                      .map{ |r| [r.scheduled_for, r] }.to_h
    count = Hash.new
    reservations.map do |date, reserv|
      count[reserv.scheduled_for] ||= 0
      count[reserv.scheduled_for] = reserv.party_size
    end
  end

  def cart_count
    $redis.scard "cart#{id}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

  def profile
    @user = current_user
  end

  def membership

  end
end

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="row">
  <h3>Users</h3>
  <div class="column">
    <table class="table">
      <tbody>
      <% @users.each do |user| %>
        <tr>
          <%= render user %>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/profile.html.erb
<div class="row">
  <div class="col-sm-6">
    <h3>User</h3>
    <p><strong>Name:</strong> <%= @user.name if @user.name %></p>
    <p><strong>Email:</strong> <%= @user.email if @user.email %></p>
    <p><strong>Account Created:</strong> <%= @user.created_at.strftime('%A, %B %d') %></p>
    <p><strong>Member:</strong> <%= @user.member? ? 'YES' : 'NO'%></p>

  </div>
  <div class="col-sm-6">
    <% if @user.member? %>
      <h3>Membership</h3>
      <p><strong>Type:</strong> <%= @user.membership_type %></p>
      <p><strong>Start Date:</strong> <%= @user.membership_start_date.strftime('%A, %B %d') %></p>
      <p><strong>End Date:</strong> <%= @user.membership_end_date.strftime('%A, %B %d') %></p>
      <p><strong>Paid:</strong> $<%= @user.total_paid %></p>
    <% else %>
      <h3>Become a Member</h3>
      <%= form_tag membership_path, method: :post do |form| %>
        <div>
          Type: <%= select_tag :type, options_for_select(User.membership_types) %><br>
          <%= hidden_field_tag :start_date, DateTime.now %>
          <br>
          <%= submit_tag 'Reserve' %>
        </div>

        <br>

        <div>
          <h5>Prices:</h5>
          <ul>
            <li>1 Month (monthly): <strong>$74</strong></li>
            <li>3 Months (quarterly): <strong>$190</strong></li>
            <li>12 Months (yearly): <strong>$720</strong></li>
          </ul>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>
<p>Account Created: <%= @user.created_at.strftime('%A, %B %d') %></p>
<p>Member: <%= @user.member? ? 'YES' : 'NO'%></p>

<% if @user.member? %>
  <p>Membership Type: <%= @user.membership_type %></p>
  <p>Membership Start Date: <%= @user.membership_start_date.strftime('%A, %B %d') %></p>
  <p>Membership End Date: <%= @user.membership_end_date.strftime('%A, %B %d') %></p>
  <p>Membership Total: $<%= @user.total_paid %></p>
<% end %>