config/routes.rb
Rails.application.routes.draw do
  get 'charges/new'

  get 'charges/create'

  get 'carts/show'

  root to: 'visitors#home'

  # ----------------- Charges ------------------
  resources :charges, only: [:new, :create]
  # --------------------------------------------

  # ------------------ Cart --------------------
  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
    get 'clear', to: 'carts#clear', as: :clear
  end
  # --------------------------------------------

  # -------------- Reservations ----------------
  resources :reservations, only: [:index, :new, :create]
  get 'reservations/table' => 'reservations#table', as: :table_reservation
  get 'reservations/lesson' => 'reservations#lesson', as: :lesson_reservation
  get 'dashboard/admin' => 'reservations#dashboard', as: :admin_dashboard
  delete 'reservations' => 'reservations#delete'
  # --------------------------------------------

  # ------------  User and Session -------------
  resources :users
  devise_for :users, skip: [:sessions]
  devise_scope :user do
    get 'signin', to: 'devise/sessions#new', as: :new_user_session
    post 'signin', to: 'devise/sessions#create', as: :user_session
    delete 'signin', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  get 'profile' => 'users#profile'
  post 'membership' => 'users#membership'
  # --------------------------------------------


  # ------------------ Products ----------------
  resources :products
  # --------------------------------------------
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' or name.to_s == 'success' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_admin.html.erb
<% if user_signed_in? and current_user.admin_role? %>
  <li><%= link_to 'Users', users_path %></li>
  <li><%= link_to 'Dashboard', admin_dashboard_path(day_id: current_dayblock_id) %></li>

  <li>
    <a href="#managementSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
      Management
    </a>
    <ul class="collapse list-unstyled" id="managementSubmenu">
      <li>
        <%= link_to 'Users', users_path %>
      </li>

      <li>
        <%= link_to 'Club', users_path %>
      </li>
    </ul>
  </li>


<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <% if current_user.admin_role? %>
<!--    <li><%#= link_to 'Users', users_path %></li>-->
    <li>
      <%= link_to 'Dashboard',
                  admin_dashboard_path(day_id: current_dayblock_id)
      %></li>
  <% end %>

  <li><%= link_to 'Settings', edit_user_registration_path %></li>
  <li><%= link_to 'Profile ( '+current_user.email+' )', reservations_path
  %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_nav_links_for_user.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Profile', profile_path %></li>

  <li><%= link_to 'Reserve Table', table_reservation_path %></li>

  <li>
    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
      Reserve Lesson
    </a>
    <ul class="collapse list-unstyled" id="pageSubmenu">
      <li>
        <%= link_to 'Coach Terese', lesson_reservation_path(coach_id: 5) %>
      </li>
      <li>
        <%= link_to 'Coach Lady', lesson_reservation_path(coach_id: 6) %>
      </li>
      <li>
        <%= link_to 'Coach David', lesson_reservation_path(coach_id: 7) %>
      </li>
    </ul>
  </li>

<!--  <li><%#= link_to 'Settings', edit_user_registration_path %></li>-->
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navbar_collapse.html.erb
<!--<nav class="navbar navbar-expand-lg navbar-light bg-light">-->
<!--  <div class="container-fluid">-->

<!--    <button type="button" id="sidebarCollapse" class="btn btn-info">-->
<!--      <i class="fa fas fa-align-left"></i>-->
<!--    </button>-->

<!--  </div>-->
<!--</nav>-->

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<style>
  .logo-sm {
    padding-left: 10px;
    height: 150px;
    width: 200px;
  }



</style>
<nav id="sidebar">
  <div class="sidebar-header">
    <div class="row">
      <%= image_tag 'logo', class: 'logo-sm' %>
      <h3 class="text-center">BTTC</h3>
    </div>
  </div>

  <ul class="list-unstyled components">
    <p>Welcome <%= current_user.name if user_signed_in? %></p>

    <li><%= link_to 'Home', root_path, class: 'nav-link'%></li>
    <li><%= link_to 'Shop', products_path, class: 'nav-link'%></li>

    <%= render 'layouts/nav_links_for_admin' %>

    <li class="divider"></li>

    <%= render 'layouts/nav_links_for_user' %>

    <li class="divider"></li>

    <%= render 'layouts/navigation_links' %>

    <% if user_signed_in? %>
      <li class="divider"></li>
      <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<li><%= link_to 'Junior Program', page_path('junior_program') %></li>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/_social_media.html.erb
<a href="https://www.youtube.com/channel/UCsHbNKJK5RFi5cBYt1PQdqg">
  <i class="fa fa-3x fa-youtube-square" style="color: #FF0000"></i>
</a>

<a href="https://www.facebook.com/2xtremepong/">
  <i class="fa fa-3x fa-facebook-square" style="color: #3b5998"></i>
</a>

<a href="https://www.instagram.com/2xtremepong/?hl=en">
  <i class="fa fa-3x fa-instagram" aria-hidden="true"></i>
</a>

<a href="https://twitter.com/2xtremepong">
  <i class="fa fa-3x fa-twitter-square" style="color: #38A1F3"></i>
</a>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "BTTC"
    %meta{content: "#{content_for?(:description) ? yield(:description) : "Rails Devise"}", name: "description"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    / <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
    = csrf_meta_tags
  %body.container
    .wrapper
      = render 'layouts/navigation'
      .row.padded
        = link_to cart_path, class: 'col-sm-2' do
          %span.fa-stack.fa-2x.has-badge{"data-count" => "#{$redis.smembers(current_user_cart).count}"}
            %i.fa.fa-shopping-cart.fa-stack-1x
        .col-sm-10.padded.text-right
          = render 'layouts/social_media'
      .padded.sidebarCollapseWrapper
        %nav.navbar.navbar-expand-lg.navbar-light.bg-light
          .container-fluid
            / <button type="button" id="sidebarCollapse" class="btn btn-info">
            / <i class="fa fas fa-align-left"></i>
            / </button>
      #content.container.padded
        = render 'layouts/messages'
        = render 'layouts/navbar_collapse'
        = yield
    / <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>